# Generated by Django 4.2.3 on 2023-07-07 07:42

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=todo.models.one_week_ago)),
                ('complete', models.BooleanField()),
            ],
        ),
    ]
