# Generated by Django 4.2.3 on 2023-07-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_task_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
